// Canonical explorer facet type IDs for Rig Veda anukramani.
// Display strings live in content/samhita/localization.vy — not here.
// Generated by enrich:rv.

`facets {
    "devata" = "devata",
    "rishi" = "rishi",
    "chandas" = "chandas"
}
