import type { EntityRegistry } from "../lib/entity-registry";
import { chandasKeyFromMeterProse } from "../lib/chandas-keys";
import {
  buildPerRikRoman,
  coalesceEqualRuns,
  triplesEqual,
  type RikAnukramaniRoman,
} from "../lib/vmlt-ranges";

export interface RikAnukramaniKeys {
  rishi: string;
  devata: string;
  chandas: string;
}

export interface AnukramaniAnnotateSpan {
  mandala: number;
  sukta: number;
  start: number;
  end: number;
  triple: RikAnukramaniKeys;
}

function registerTriple(
  registry: EntityRegistry,
  roman: RikAnukramaniRoman,
): RikAnukramaniKeys | null {
  const rishi = roman.rishi ? registry.registerRoman(roman.rishi, "entity") : "";
  const devata = roman.devata ? registry.registerRoman(roman.devata, "entity") : "";
  let chandas = "";
  if (roman.chandas) {
    const mapped = chandasKeyFromMeterProse(roman.chandas);
    if (mapped) {
      chandas = registry.registerChandasKey(
        mapped.key,
        mapped.label,
        roman.chandas,
      );
    } else {
      chandas = registry.registerRoman(roman.chandas, "meter");
    }
  }
  if (!rishi || !devata || !chandas) return null;
  return { rishi, devata, chandas };
}

export function buildAnukramaniSpans(
  mandala: string,
  sukta: string,
  rikCount: number,
  info: { from?: string; to?: string; meters?: string },
  registry: EntityRegistry,
): AnukramaniAnnotateSpan[] {
  const m = Number.parseInt(mandala, 10);
  const s = Number.parseInt(sukta, 10);
  const romanByRik = buildPerRikRoman(info, rikCount);

  const keysByRik = new Map<number, RikAnukramaniKeys>();
  for (let rik = 1; rik <= rikCount; rik++) {
    const roman = romanByRik.get(rik) ?? {};
    const keys = registerTriple(registry, roman);
    if (keys) keysByRik.set(rik, keys);
  }

  const runs = coalesceEqualRuns(
    rikCount,
    (rik) => keysByRik.get(rik),
    triplesEqual,
  );

  return runs.map((run) => ({
    mandala: m,
    sukta: s,
    start: run.start,
    end: run.end,
    triple: run.value,
  }));
}

export function formatUrnSpan(
  mandala: number,
  sukta: number,
  start: number,
  end: number,
): string {
  if (start === end) return `${mandala}:${sukta}:${start}`;
  return `${mandala}:${sukta}:${start}..${mandala}:${sukta}:${end}`;
}

export function formatAnnotateLine(span: AnukramaniAnnotateSpan): string {
  const urn = formatUrnSpan(span.mandala, span.sukta, span.start, span.end);
  const { rishi, devata, chandas } = span.triple;
  return `\`annotate "${urn}" { rishi=${rishi}, devata=${devata}, chandas=${chandas} }`;
}

export function formatMandalaAnnotationsFile(
  mandala: string,
  lines: string[],
  snapshotDate: string,
): string {
  const m = Number.parseInt(mandala, 10);
  const header = [
    "`title [Rig Veda Mandala " + m + " — Anukramani]",
    "",
    "// Generated by enrich:rv from VMLT snapshot (" + snapshotDate + ").",
    "// Canonical anukramani: graph edges via `annotate` (not Wikisource HTML).",
    "",
  ];
  return `${header.join("\n")}${lines.join("\n")}\n`;
}

export function formatEntitiesVocabulary(registry: EntityRegistry): string {
  const lines = [
    "// Canonical entity keys for anukramani graph edges (RFC-019 registry).",
    "// Devanagari display labels; generated by enrich:rv.",
    "",
    "`entities {",
  ];
  for (const record of registry.entitiesOnly()) {
    lines.push(`    "${record.key}" = "${record.label.replace(/"/g, '\\"')}"`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

/** Static facet type registry — display labels live in content/samhita/localization.vy. */
export function formatFacetsVocabulary(): string {
  return [
    "// Canonical explorer facet type IDs for Rig Veda anukramani.",
    "// Display strings live in content/samhita/localization.vy — not here.",
    "// Generated by enrich:rv.",
    "",
    "`facets {",
    '    "devata" = "devata",',
    '    "rishi" = "rishi",',
    '    "chandas" = "chandas"',
    "}",
    "",
  ].join("\n");
}

export function formatMetersVocabulary(registry: EntityRegistry): string {
  const lines = [
    "// Canonical chandas (meter) keys for anukramani graph edges.",
    "// Generated by enrich:rv.",
    "",
    "`entities {",
  ];
  for (const record of registry.metersOnly()) {
    lines.push(`    "${record.key}" = "${record.label.replace(/"/g, '\\"')}"`);
  }
  lines.push("}", "");
  return lines.join("\n");
}
